### ISSUE TITLE
ConsumerWithDelegate with ComposedClosure will throw exception.

### ISSUE THREAD

**Issue by chunlinyao** [dsl-builders/groovy-closure-support#6]
When work with ComposedClosure, it thrown ClassCastException.
Because ComposedClosure overrided setResolveStrategy method, cast its getOwner to Closure. Which be replaced by an outer class.

```
java.lang.ClassCastException: java.lang.Class cannot be cast to groovy.lang.Closure
        at org.codehaus.groovy.runtime.ComposedClosure.setResolveStrategy(ComposedClosure.java:81) ~[groovy-2.5.14.jar:2.5.14]
        at space.jasan.support.groovy.closure.ConsumerWithDelegate.accept(ConsumerWithDelegate.java:38) ~[groovy-closure-support-0.6.0.jar:?]
```

**Comment by musketyr** [comment]
Thank you for reporting. I will take a look during this week.

**Comment by chunlinyao** [comment]
It looks like a bug in groovy.

Vladimir Orany ***@***.***> 于2021年5月12日周三 下午4:11写道：

**Comment by musketyr** [comment]
I'm afraid, there is nothing I can do in the library side. Do you have some example of usage?

**Comment by chunlinyao** [comment]
I have some common logic inadition to some different closure, so I use >>
operator to create composed closure.

I created a bug report for groovy.
https://issues.apache.org/jira/browse/GROOVY-10083

Vladimir Orany ***@***.***> 于 2021年5月13日周四 下午4:46写道：
